### ISSUE TITLE
整体布局修改

### ISSUE THREAD

**Issue by RainyNight9** [Hongbusi/vue-hbs-admin#16]
### Clear and concise description of the problem

头部导航应该占全部窗口宽度 100%

左侧菜单 应该在导航下边 整体高度是 窗口高度 减去 头部导航高度 

收起/展开 左侧菜单按钮应该 固定放在左侧菜单最下边

这样的布局 有利于 做微前端、统一导航...

**Comment by Hongbusi** [comment]
目前是不建议去动布局、导航功能的。

### 当前计划

目前是选择优先去做组件功能，提供多的解决方案。因为这里的效果更佳显著，且在后续计划中，组件和 Demo 不会产生什么影响。

### 后续计划

后续会针对 `layout` 做优化，详见 [pro-antdv 示例](https://preview.pro.antdv.com)。
