### ISSUE TITLE
全屏

### ISSUE THREAD

**Issue by Hongbusi** [Hongbusi/vue-hbs-admin#23]
### Clear and concise description of the problem

[useFullscreen](https://vueuse.org/core/useFullscreen)

**Comment by alexzhang1030** [comment]
做好的功能就可以 close 了吧

**Comment by Hongbusi** [comment]
这个还没做，只是贴了一下实现方案

**Comment by alexzhang1030** [comment]
原来如此

**Comment by alexzhang1030** [comment]
我领了，明天做一下
